### ISSUE TITLE
policy(precheck): dependency-scan.sh blocks on any HIGH/CRITICAL finding, even with no fix available — was this a deliberate tightening?

### ISSUE THREAD

**Issue by bakeb7j0** [Wave-Engineering/claudecode-workflow#1188]
## Summary

Before #1137, /precheck's Job C dependency scan was prose asking a sub-agent to report findings, with the documented policy: "Do NOT block the gate on vulnerabilities with no available fix." That leniency existed because an unfixable transitive CVE has no immediate remediation — blocking on it forces editing the check itself as the only way forward.

`scripts/ci/dependency-scan.sh` (introduced in #1137) exits 1 (FAIL) on ANY HIGH/CRITICAL finding regardless of `FixedVersion` availability — it does not implement `--ignore-unfixed` or honor a `.trivyignore`. `validate.sh` counts that exit code as a hard failure. This is a real behavior change, not just a stale doc: the gate got stricter when the check moved from agent judgment to a deterministic script, and nobody decided that on purpose.

Found during #1137's merge-conflict-resolution code review (confidence 70, reviewer's finding #6); `skills/precheck/SKILL.md`'s prose has been updated to state the current (stricter) behavior honestly rather than the stale promise, pending this decision.

## Changes

Two options, roughly in order of effort:
1. **Accept the tightening.** Keep current behavior (any HIGH/CRITICAL blocks), update all references to the old "no-fix doesn't block" promise repo-wide (there may be more than the one caught here), and close this as "working as intended, decided."
2. **Restore the old leniency.** Add `--ignore-unfixed` to the trivy invocation in `dependency-scan.sh` (or parse `FixedVersion` per-finding and only fail on findings that have one), and cover it with tests. Note: `--ignore-unfixed` is a blunt instrument — it suppresses unfixed findings from the report entirely, not just from the exit code, so an alternative is parsing `Vulnerabilities[].FixedVersion` per-finding and separating "blocks the gate" from "reported but does not block."

## Test Procedures

Whichever direction: a stub-trivy test asserting a no-fix-available finding either does or does not fail the gate, matching the decided policy — mirroring the existing stub tests in `tests/test_dependency_scan.py`.

## Acceptance Criteria

- [ ] A decision is made and recorded (comment on this issue, or the commit message of whichever PR closes it).
- [ ] `dependency-scan.sh`'s behavior matches `skills/precheck/SKILL.md`'s stated policy — no gap between what the docs promise and what the tool does.
- [ ] Covered by a stub-based test proving the decided behavior.

## Related

Found during #1137 (fix/1137-post-scan-denominator)'s merge-conflict resolution and code review.
